name: Deploy to CloudBase Static Hosting

on:
  push:
    branches:
      - main # 主分支推送时触发
  pull_request:
    branches:
      - main # PR时触发（可选）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.13'
        cache: 'yarn' # 按照 yarn.lock 缓存依赖以加速构建

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build project
      run: yarn build

    - name: Install CloudBase CLI
      run: npm install -g @cloudbase/cli

    - name: Login CloudBase CLI
      run: tcb login --apiKeyId ${{ secrets.TCB_SECRET_ID }} --apiKey ${{ secrets.TCB_SECRET_KEY }}

    - name: Deploy to CloudBase Static Hosting
      run: tcb hosting deploy ./out -e ${{ secrets.TCB_ENV_ID }}


    # - name: Deploy via SSH
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.EC2_HOST }}
    #     username: ${{ secrets.EC2_USER }}
    #     key: ${{ secrets.EC2_SSH_KEY }}
    #     port: ${{ secrets.EC2_PORT }}
    #     script: |
    #       set -ex
    #       pkill -f next || true
    #       rsync -avz --delete ./ $HOME/hongdong_website/
    #       cd $HOME/hongdong_website
    #       yarn install
    #       # use pm2 to start/restart
    #       # pm2 restart hongdong_website || pm2 start npm --name "hongdong_website" -- start
    #       # pm2 save
    #       # sleep 10  # Allows server to start before disconnect
    #       # pm2 list
